services:
  - type: web
    name: diamond-ai-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=1
    envVars:
      - key: OPENAI_API_KEY
        sync: false
